# Generated by Django 4.0.1 on 2022-02-11 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0004_remove_ledger_organisation_ledger_address_one_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cummunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True)),
                ('subject', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('kind', models.PositiveSmallIntegerField(choices=[(1, 'Meeting'), (2, 'Phone'), (3, 'Email')], max_length=1)),
                ('date', models.DateField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('ledger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.ledger')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
