# Generated by Django 4.0.1 on 2022-02-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cummunication',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Meeting'), (2, 'Phone'), (3, 'Email')]),
        ),
    ]
