# Generated by Django 4.0.1 on 2022-02-17 20:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_remove_client_organisation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Customer',
        ),
    ]
