# Generated by Django 4.0.1 on 2022-03-17 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_client_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
