# Generated by Django 4.0.1 on 2022-02-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='last_name',
        ),
        migrations.AddField(
            model_name='ledger',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
