# Generated by Django 4.0.1 on 2022-02-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_remove_ledger_first_name_remove_ledger_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
