# Generated by Django 4.0.1 on 2022-02-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_ledger_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='organisation',
        ),
        migrations.AddField(
            model_name='ledger',
            name='address_one',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledger',
            name='address_two',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ledger',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledger',
            name='state',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
